<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PhoneDisplay.Server</RootNamespace>
    <AssemblyName>PhoneDisplay.Server</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\web\index.html" LogicalName="PhoneDisplay.Server.www.index.html" />
    <EmbeddedResource Include="..\web\player.css" LogicalName="PhoneDisplay.Server.www.player.css" />
    <EmbeddedResource Include="..\web\player.js" LogicalName="PhoneDisplay.Server.www.player.js" />
  </ItemGroup>

</Project>